# Generated by Django 5.0.7 on 2024-07-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CadastroCliente",
        ),
        migrations.DeleteModel(
            name="CadastroFormulario",
        ),
    ]
